config/routes.rb
Spree::Core::Engine.routes.prepend do
  resources :addresses
end

app/models/spree/address_ability.rb
class Spree::AddressAbility
  include CanCan::Ability

  def initialize(user)
    can :manage, Spree::Address do |address|
      address.user == user
    end

    can :create, Spree::Address do |address|
      user.id.present?
    end
  end
end

app/models/spree/address_decorator.rb
Spree::Address.class_eval do
  belongs_to :user, :class_name => Spree.user_class.to_s

  attr_accessible :user_id, :deleted_at

  def self.required_fields
    validator = Spree::Address.validators.find{|v| v.kind_of?(ActiveModel::Validations::PresenceValidator)}
    validator ? validator.attributes : []
  end
  
  # TODO: look into if this is actually needed. I don't want to override methods unless it is really needed
  # can modify an address if it's not been used in an order
  def same_as?(other)
    return false if other.nil?
    attributes.except('id', 'updated_at', 'created_at', 'user_id') == other.attributes.except('id', 'updated_at', 'created_at', 'user_id')
  end
  
  # can modify an address if it's not been used in an completed order
  def editable?
    new_record? || (shipments.empty? && Spree::Order.complete.where("bill_address_id = ? OR ship_address_id = ?", self.id, self.id).count == 0)
  end

  def can_be_deleted?
    shipments.empty? && Spree::Order.where("bill_address_id = ? OR ship_address_id = ?", self.id, self.id).count == 0
  end

  def to_s
    [
      "#{firstname} #{lastname}",
      "#{address1}",
      "#{address2}",
      "#{city}, #{state || state_name} #{zipcode}",
      "#{country}"
    ].reject(&:empty?).join("<br/>").html_safe
  end

  # UPGRADE_CHECK if future versions of spree have a custom destroy function, this will break
  def destroy
    if can_be_deleted?
      super
    else
      update_column :deleted_at, Time.now
    end
  end
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do
  attr_accessible :bill_address_id, :ship_address_id
  before_validation :clone_shipping_address, :if => "Spree::AddressBook::Config[:disable_bill_address]"
  
  def clone_shipping_address
    if self.ship_address
      self.bill_address = self.ship_address
    end
    true
  end
  
  def clone_billing_address
    if self.bill_address
      self.ship_address = self.bill_address
    end
    true
  end
  
  def bill_address_id=(id)
    address = Spree::Address.where(:id => id).first
    if address && address.user_id == self.user_id
      self["bill_address_id"] = address.id
      self.bill_address.reload
    else
      self["bill_address_id"] = nil
    end
  end
  
  def bill_address_attributes=(attributes)
    self.bill_address = update_or_create_address(attributes)
  end

  def ship_address_id=(id)
    address = Spree::Address.where(:id => id).first
    if address && address.user_id == self.user_id
      self["ship_address_id"] = address.id
      self.ship_address.reload
    else
      self["ship_address_id"] = nil
    end
  end
  
  def ship_address_attributes=(attributes)
    self.ship_address = update_or_create_address(attributes)
  end
  
  private
  
  def update_or_create_address(attributes)
    if attributes[:id]
      address = Spree::Address.find(attributes[:id])
      attributes.delete(:id)

      if address && address.editable?
        address.update_attributes(attributes)
      else
        attributes.delete(:id)
      end
    end

    if !attributes[:id]
      address = Spree::Address.new(attributes)
      address.save
    end
    
    address
  end
    
end

app/models/spree/user_decorator.rb
Spree.user_class.class_eval do
  has_many :addresses, :conditions => {:deleted_at => nil}, :order => "updated_at DESC", :class_name => 'Spree::Address'
end

app/controllers/spree/addresses_controller.rb
class Spree::AddressesController < Spree::StoreController
  helper Spree::AddressesHelper
  rescue_from ActiveRecord::RecordNotFound, :with => :render_404
  load_and_authorize_resource :class => Spree::Address

  def index
    redirect_to account_path
  end
  
  def show
    redirect_to account_path
  end

  def edit
    session["user_return_to"] = request.env['HTTP_REFERER']
  end

  def new
    @address = Spree::Address.default
  end

  def update
    if @address.editable?
      if @address.update_attributes(params[:address])
        flash[:notice] = I18n.t(:successfully_updated, :resource => I18n.t(:address))
        redirect_back_or_default(account_path)
      else
        render :action => "edit"
      end
    else
      new_address = @address.clone
      new_address.attributes = params[:address]
      @address.update_attribute(:deleted_at, Time.now)
      if new_address.save
        flash[:notice] = I18n.t(:successfully_updated, :resource => I18n.t(:address))
        redirect_back_or_default(account_path)
      else
        render :action => "edit"
      end
    end
  end

  def create
    @address = Spree::Address.new(params[:address])
    @address.user = current_user
    if @address.save
      flash[:notice] = I18n.t(:successfully_created, :resource => I18n.t(:address))
      redirect_to account_path
    else
      render :action => "new"
    end
  end

  def destroy
    @address.destroy

    flash[:notice] = I18n.t(:successfully_removed, :resource => t(:address))
    redirect_to(request.env['HTTP_REFERER'] || account_path) unless request.xhr?
  end
end

app/controllers/spree/checkout_controller_decorator.rb
Spree::CheckoutController.class_eval do
  helper Spree::AddressesHelper
  
  after_filter :normalize_addresses, :only => :update
  before_filter :set_addresses, :only => :update
  
  protected
  
  def set_addresses
    return unless params[:order] && params[:state] == "address"
    
    if params[:order][:ship_address_id].to_i > 0
      params[:order].delete(:ship_address_attributes)

      Spree::Address.find(params[:order][:ship_address_id]).user_id != spree_current_user.id && raise("Frontend address forging")
    else
      params[:order].delete(:ship_address_id)
    end
    
    if params[:order][:bill_address_id].to_i > 0
      params[:order].delete(:bill_address_attributes)

      Spree::Address.find(params[:order][:bill_address_id]).user_id != spree_current_user.id && raise("Frontend address forging")
    else
      params[:order].delete(:bill_address_id)
    end
    
  end

  def normalize_addresses
    return unless params[:state] == "address" && @order.bill_address_id && @order.ship_address_id
    return if (@order.bill_address.id.nil? || @order.ship_address.nil?)

    @order.bill_address.reload
    @order.ship_address.reload
    
    # ensure that there is no validation errors and addresses was saved
    return unless @order.bill_address && @order.ship_address
    
    if @order.bill_address_id != @order.ship_address_id && @order.bill_address.same_as?(@order.ship_address)
      @order.bill_address.destroy
      @order.update_attribute(:bill_address_id, @order.ship_address.id)
    else
      @order.bill_address.update_attribute(:user_id, spree_current_user.try(:id))
    end
    @order.ship_address.update_attribute(:user_id, spree_current_user.try(:id))
  end
end

app/helpers/spree/addresses_helper.rb
module Spree::AddressesHelper
  def address_field(form, method, id_prefix = "b", &handler)
    id_prefix = id_prefix == 'bill_address' ? 'b' : 's'
    content_tag :p, :id => [id_prefix, method].join, :class => "field" do
      if handler
        handler.call
      else
        is_required = Spree::Address.required_fields.include?(method)
        separator = is_required ? '<span class="req">*</span><br />' : '<br />'
        form.label(method) + separator.html_safe +
        form.text_field(method, :class => is_required ? 'required' : nil)
      end
    end
  end

  def address_state(form, country)
    country ||= Spree::Country.find(Spree::Config[:default_country_id])
    have_states = !country.states.empty?
    state_elements = [
      form.collection_select(:state_id, country.states.order(:name),
                            :id, :name,
                            {:include_blank => true},
                            {:class => have_states ? "required" : "hidden",
                            :disabled => !have_states}) +
      form.text_field(:state_name,
                      :class => !have_states ? "required" : "hidden",
                      :disabled => have_states)
      ].join.gsub('"', "'").gsub("\n", "")

    form.label(:state, t(:state)) + '<span class="req">*</span><br />'.html_safe +
      content_tag(:noscript, form.text_field(:state_name, :class => 'required')) +
      javascript_tag("document.write(\"#{state_elements.html_safe}\");")
  end
end

app/views/spree/addresses/_form.html.erb
<% address_id = address_type.chars.first %>
<% country_id = address_type == 'billing' ? 'bcountry' : 'scountry' %>
<% ADDRESS_FIELDS.each do |field| %>
  <% if field == "country" %>

  <p class="field" id=<%="#{address_id}country" %>>
    <%= address_form.label :country_id, t(:country) %><span class="required">*</span><br />
    <span id=<%="#{address_id}country-selection" %>>
      <%= address_form.collection_select :country_id, available_countries, :id, :name, {}, {:class => 'required'} %>
    </span>

  </p>
  <% elsif field == "state" && Spree::Config[:address_requires_state] %>

    <p class="field" id=<%="#{address_id}state" %>>
      <% have_states = !address.country.states.empty? %>
      <%= address_form.label :state, t(:state) %><span class='required' id=<%="#{address_id}state-required"%>>*</span><br/>

      <% state_elements = [
         address_form.collection_select(:state_id, address.country.states,
                            :id, :name,
                            {:include_blank => true},
                            {:class => have_states ? 'required' : 'hidden',
                            :disabled => !have_states}) +
         address_form.text_field(:state_name,
                            :class => !have_states ? 'required' : 'hidden',
                            :disabled => have_states)
         ].join.gsub('"', "'").gsub("\n", "")
      %>
      <%= javascript_tag do -%>
        $('#<%="#{address_id}state" %>').append("<%== state_elements %>");
      <% end %>
    </p>
      <noscript>
        <%= address_form.text_field :state_name, :class => 'required' %>
      </noscript>

  <% else %>
    <% next if field == "company" && !Spree::Config[:company] %>
    <%= address_field(address_form, field.to_sym, address_name) %>
  <% end %>
<% end %>
<% if Spree::Config["alternative_#{address_name[0] == 'b' ? 'billing' : 'shipping'}_phone"] %>
  <%= address_field(address_form, :alternative_phone, address_name) %>
<% end %>

app/views/spree/addresses/destroy.js.erb
$("#billing_address_<%= @address.id %>").fadeOut();
$("#shipping_address_<%= @address.id %>").fadeOut();

app/views/spree/addresses/edit.html.erb
<% content_for :head do %>
  <%= javascript_include_tag states_url(:format => :js) %>
  <%= javascript_include_tag countries_url(:format => :js) %>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @address } %>
<%= form_for @address, :html => { :id => "checkout_form_address"} do |f| %>
<fieldset>
  <%= content_tag(:legend, Spree.t(:edit_shipping_address, :scope => :address_book)) %>
  <div class="inner">
    <%= render :partial => 'spree/addresses/form', :locals => {
      :address_name => 'address',
      :address_form => f,
      :address_type => 'shipping',
      :address => @address
    } %>
  </div>
  <%= f.submit Spree.t(:update) %>
</fieldset>
<% end %>

app/views/spree/addresses/new.html.erb
<% content_for :head do %>
  <%= javascript_include_tag states_url(:format => :js) %>
  <%= javascript_include_tag countries_url(:format => :js) %>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @address } %>
<%= form_for @address, :html => {:id => "checkout_form_address"} do |f| %>
<fieldset>
  <%= content_tag(:legend, t(:new_shipping_address, :scope => :address_book)) %>
  <div class="inner">
    <%= render :partial => 'spree/addresses/form', :locals => {
      :address_name => 'address',
      :address_form => f,
      :address_type => 'shipping',
      :address => @address
    } %>
  </div>
  <%= f.submit t(:save, :scope => :address_book) %>
</fieldset>
<% end %>

app/views/spree/checkout/_address.html.erb
<% @addresses = spree_current_user ? spree_current_user.addresses : [] %>

<% ['billing', 'shipping'].each do |address_type|
  next if address_type == 'billing' && Spree::AddressBook::Config[:disable_bill_address]
  address_name = "#{address_type[0...4]}_address" %>
<div class="columns alpha six" data-hook="<%= address_type %>_fieldset_wrapper">
<fieldset id="<%= address_type %>">
  <legend><%= t(address_type + "_address")%></legend>
  <% if address_type == 'shipping' && !Spree::AddressBook::Config[:disable_bill_address] %>
    <p class="field checkbox"  data-hook="use_billing">
      <%= check_box_tag 'order[use_billing]', '1', (!(@order.bill_address.empty? && @order.ship_address.empty?) && @order.bill_address.same_as?(@order.ship_address)) %> 
      <%= label_tag :order_use_billing, Spree.t(:use_billing_address), :id => 'use_billing' %>
    </p>
  <% end %>
  <% if @addresses.present? %>
  <div class="select_address">
    <p class="field">
      <% @addresses.each_with_index do |address, idx| %>
      <span id="<%= [address_type, dom_id(address)].join('_') %>">
        <label><%= form.radio_button "#{address_name}_id", address.id, :checked => (idx == 0) %> <%= address %></label> <%= link_to t(:edit), edit_address_path(address) %><br />
      </span>
      <% end %>
      <label><%= form.radio_button "#{address_name}_id", 0 %> <%= Spree.t('other_address', :scope => :address_book) %></label>
    </p>
  </div>
  <% end %>
  <%= form.fields_for address_name do |address_form| %>
    <div class="inner" data-hook=<%="#{address_type}_inner" %>>
      <%= render :partial => 'spree/addresses/form', :locals => {
        :address_name => address_name,
        :address_form => address_form,
        :address_type => address_type,
        :address => Spree::Address.default
      } %>
    </div>
  <% end %>
</fieldset>
</div>
<% end %>

<hr class="clear" />
<div class="form-buttons" data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), :class => 'continue button primary' %>
</div>

app/views/spree/users/_addresses.html.erb
<h3><%= t(:shipping_addresses, :scope => :address_book) %></h3>
<% if spree_current_user.addresses.present? %>
<table id="user_addresses">
  <tbody>
    <% spree_current_user.addresses.each do |address| %>
    <tr class="<%= cycle('even', 'odd') %>">
      <td><%= address %></td>
      <td>
        <%= link_to t(:edit), edit_address_path(address) %>&nbsp;
        <%= link_to t(:remove), address_path(address), :method => :delete, :confirm => t(:are_you_sure) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<div id="users-address-list-empty">
  <%= t(:no_shipping_addresses_on_file, :scope => :address_book) %>
</div>
<% end %>
<div id="new_address_link">
  <%= link_to t(:add_new_shipping_address, :scope => :address_book), :controller => :addresses, :action => :new %>
</div>